In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [44]:
from word2number import w2n

In [3]:
df = pd.read_csv('..\\ML\\2_linear_reg_multivariate\\homeprices.csv')

In [4]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
import math
bedrooms = math.floor(df.bedrooms.median())
# bedroom = bedrooms -1

In [16]:
df.bedrooms = df.bedrooms.fillna(bedrooms)

In [17]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [22]:
reg = linear_model.LinearRegression()
reg.fit(df.iloc[:,0:3], df[['price']])

LinearRegression()

In [35]:
reg.predict([[3000, 4, 15]])

array([[602590.07937407]])

In [26]:
df[['area', 'age']]

area  age
0  2600   20
1  3000   15
2  3200   18
3  3600   30
4  4000    8
5  4100    8

In [36]:
reg.coef_

array([[  112.06244194, 23388.88007794, -3231.71790863]])

In [31]:
reg.intercept_

array([221323.0018654])

In [39]:
3000*112.06244194+4*23388.88007794-3231.71790863*15+221323.0018654

602590.07936771

In [40]:
df1 = pd.read_csv('..\\ML\\2_linear_reg_multivariate\\Exercise\\hiring.csv')

In [41]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [46]:
df1.experience

0       NaN
1       NaN
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [42]:
!pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5595 sha256=2b1f8eccb62ea51e3db8087838b857e2a3986773796c720f060fd8b0a200441f
  Stored in directory: c:\users\ip330s\appdata\local\pip\cache\wheels\cb\f3\5a\d88198fdeb46781ddd7e7f2653061af83e7adb2a076d8886d6
Successfully built word2number


In [60]:
li = []
for i in df1.experience:
    li.append(w2n.word_to_num(i))

In [61]:
li

[0, 0, 5, 2, 7, 3, 10, 11]

In [54]:
for i in df1.experience:
    print(i)

zero
zero
five
two
seven
three
ten
eleven


In [52]:
df1.experience = df1.experience.fillna('zero')

In [53]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [62]:
df1.experience = li

In [79]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [70]:
df1['test_score(out of 10)']=df1['test_score(out of 10)'].fillna(df1['test_score(out of 10)'].median())

In [75]:
reg1 = linear_model.LinearRegression()
reg1.fit(df1.iloc[:,0:3], df1['salary($)'])

LinearRegression()

In [77]:
reg1.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [78]:
reg1.intercept_

17737.26346433771

In [80]:
reg1.predict([[2, 9,6]])

array([53205.96797671])

In [81]:
reg1.predict([[12,10,10]])

array([92002.18340611])