In [1]:
import numpy as np

In [2]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
listarray.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [57]:
listarray.dtype

dtype('int32')

In [58]:
listarray.shape

(3, 3)

In [59]:
listarray.size

9

In [60]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
rng = np.arange(1,50,3)

In [62]:
rng

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [63]:
lspace = np.linspace(1,4,4)

In [64]:
lspace

array([1., 2., 3., 4.])

In [65]:
emp =  np.empty((4,6))
emp

array([[4.67296746e-307, 1.69121096e-306, 1.05697799e-307,
        6.23059725e-307, 1.06811422e-306, 3.56043054e-307],
       [1.37961641e-306, 8.06613040e-308, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.60217812e-306,
        1.37961370e-306, 1.02359848e-306, 1.60219035e-306],
       [1.60220393e-306, 1.05700515e-307, 1.11261774e-306,
        8.34423917e-308, 2.12203497e-312, 2.56765117e-312]])

In [66]:
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
arr = np.arange(1,37,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35])

In [68]:
arr = arr.reshape(6,3)

In [69]:
arr

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [70]:
arr = arr.ravel()
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35])

In [71]:
arr.shape

(18,)

In [72]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35])

In [73]:
new_arr = np.arange(1,10)
new_arr = new_arr.reshape(3,3)

In [74]:
new_arr.sum(axis=0)

array([12, 15, 18])

In [75]:
new_arr.sum(axis=1)

array([ 6, 15, 24])

In [76]:
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
new_arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [78]:
new_arr.flat

In [79]:
for i in new_arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [80]:
new_arr.ndim

2

In [81]:
new_arr.size

9

In [82]:
new_arr.nbytes

36

In [83]:
one = np.array([1,3,4,6,4555,6])
one.argmax()

4

In [84]:
one.argmin()

0

In [85]:
one.argsort()

array([0, 1, 2, 3, 5, 4], dtype=int32)

In [86]:
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
new_arr.argmax(axis=1)

array([2, 2, 2], dtype=int32)

In [88]:
new_arr.argmin(axis=0)

array([0, 0, 0], dtype=int32)

In [89]:
new_arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int32)

In [90]:
new_arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int32)

In [91]:
new_arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
new_arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [93]:
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
ar = np.array(
    [[1, 2, 3],
     [4, 2, 4],
     [2, 1, 2]])

In [95]:
new_arr + ar

array([[ 2,  4,  6],
       [ 8,  7, 10],
       [ 9,  9, 11]])

In [96]:
a = new_arr * ar

In [97]:
np.sqrt(new_arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [98]:
ar.sum()

21

In [99]:
ar.max()

4

In [100]:
ar.min()

1

In [101]:
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
array = np.arange(9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [103]:
array = array.reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
np.count_nonzero(array)

8

In [105]:
np.where(array>5)

(array([2, 2, 2], dtype=int32), array([0, 1, 2], dtype=int32))

In [106]:
array[1,2]=2

In [122]:
array

array([[0, 1, 2],
       [3, 4, 2],
       [6, 7, 3]])

In [138]:
array[1:3,1:3]=4
array.argmax()
row[max]

6

In [140]:
import sys

In [145]:
py_ar = [5,2,4,26,246,12]
np_ar = np.array(py_ar)

In [146]:
sys.getsizeof(1)*len(py_ar)

84

In [147]:
np_ar.itemsize*np_ar.size

24

In [150]:
np_ar.itemsize

4

In [152]:
import pandas as pd

In [154]:
np.version.version

'1.19.0'